blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/komikku-app/anikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in the komikku repository instead
  - name: 🖥️ Anikku website
    url: https://anikku-app.github.io/
    about: Guides, troubleshooting, and answers to common questions
